export const ADD_EMP_BASIC_DETAILS = 'ADD_EMP_BASIC_DETAILS';
export const ADD_JOB_DETAILS = 'ADD_JOB_DETAILS';
export const ADD_JOB_FILLING = 'ADD_JOB_FILLING';
export const ADD_SALARY_DETAILS = 'ADD_SALARY_DETAILS';
