export const ADD_EMP_BASIC_DETAILS = 'ADD_EMP_BASIC_DETAILS';
export const UPDATE_EMP_BASIC_DETAILS = 'UPDATE_EMP_BASIC_DETAILS';
export const ADD_JOB_DETAILS = 'ADD_JOB_DETAILS';
export const UPDATE_JOB_DETAILS = 'UPDATE_JOB_DETAILS';
export const ADD_JOB_FILLING = 'ADD_JOB_FILLING';
export const UPDATE_JOB_FILLING = 'UPDATE_JOB_FILLING';
export const ADD_SALARY_DETAILS = 'ADD_SALARY_DETAILS';
export const UPDATE_SALARY_DETAILS = 'UPDATE_SALARY_DETAILS';
